name: Supabase Database Heater

on:
  schedule:
    - cron: '0 9 * * 1,4' # Berjalan setiap Senin dan Kamis pukul 9:00 AM UTC
  workflow_dispatch: # Memungkinkan untuk menjalankan secara manual dari GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase API
        run: curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/projects?apikey=${{ secrets.SUPABASE_ANON_KEY }}"
